/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -T -t s 
Files: scene.gltf [23.17KB] > /Users/jacksontaylor/Downloads/crt_tv/scene-transformed.glb [507.56KB] (-2091%)
Author: Timothy Ahene (https://sketchfab.com/timothyahene)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/crt-tv-9ba4baa106e64319a0b540cf0af5aa9e
Title: CRT TV
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
  }
  materials: {
    TVback: THREE.MeshStandardMaterial
    TVfront: THREE.MeshStandardMaterial
    TVScreen: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.TVback} position={[0, 0.268, 0]} rotation={[Math.PI, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.TVfront} position={[0, 0.268, 0]} rotation={[Math.PI, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.TVScreen} position={[0, 0.268, 1.666]} rotation={[Math.PI, 0, Math.PI]} scale={3.982} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
